In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<h2>Upload PDF for book</h2>

In [ ]:
file_path = '/content/data-hamza.pdf'

# Open and read the file with a different encoding
with open(file_path, 'r', encoding='utf-8') as file:
    content = file.read()

# Print the content
print(content)

In [ ]:
from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
    print(f'Uploaded file: {filename}')

<h2>Parsing Data</h2>

1. Converting pdf to csv
2. Removing Special Characters
3. Adding embeddings

In [ ]:
!pip install pdfplumber
import csv
import pdfplumber
import re

def remove_special_characters(string):
    pattern = r'[^a-zA-Z0-9\s\.,!?\n]'  # Pattern to match special characters
    return re.sub(pattern, '', string)

def convert_pdf_to_csv(pdf_path, csv_path):
    with pdfplumber.open(pdf_path) as pdf:
        with open(csv_path, 'w', newline='') as csv_file:
            writer = csv.writer(csv_file,escapechar="\\")
            writer.writerow(['Page Number', 'Page Text'])

            for page_number, page in enumerate(pdf.pages, start=1):
                page_text = remove_special_characters(page.extract_text())
                writer.writerow([page_number, page_text])

#file_name= next(iter(uploaded))

# Provide the paths for the PDF and CSV files
pdf_file_path = 'data-1.pdf'
csv_file_path = 'dataset-1.csv'

# Call the function to convert PDF to CSV
convert_pdf_to_csv(pdf_file_path, csv_file_path)

<h3>Visualize the CSV file</h3>

In [ ]:
import pandas as pd
dataset = pd.read_csv('dataset-1.csv')
dataset.head()

   Page Number                                          Page Text
0            2  We\nAIM\nHIGHER\nThe National University of Sc...
1            3  Table of Content\n1 The University 1\n1. NUST ...
2            4  4 Award of Master Degrees in Business 21\nAdmi...
3            5  8 NUST Social Media Accounts and IT Services 5...
4            6  CHAPTER 1\nThe University\n1. NUST at a Glance...

<h2>Getting embeddings for all pages</h2>

In [ ]:
# removing first page img

import pandas as pd

# Read the dataset.csv file into a DataFrame
file_path = 'dataset-1.csv'
df = pd.read_csv(file_path)

# Check if there's more than one row in the DataFrame
if len(df) > 1:
    # Remove the first row (index 0) and reset the index
    df = df.iloc[1:].reset_index(drop=True)

    # Save the updated DataFrame back to the CSV file without the first row
    df.to_csv(file_path, index=False)
    print("First row removed successfully.")
else:
    print("There is only one row or the file is empty.")

First row removed successfully.

In [ ]:
!pip install --upgrade pip
!pip install openai
!pip install typing_extensions==4.7.1
!pip install typing_extensions --upgrade
!pip install openai --upgrade
!pip install requests

Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.3.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.26.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (1.10.13)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.1)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.6)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting typing_extensions==4.7.1
  Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Installing collected packages: typing_extensions
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.9.0
    Uninstalling typing_extensions-4.9.0:
      Successfully uninstalled typing_extensions-4.9.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.7.1 which is incompatible.
Successfully installed typing_extensions-4.7.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.10/dist-packages (4.7.1)
Collecting typing_extensions
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Installing collected packages: typing_extensions
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
      Successfully uninstalled typing_extensions-4.7.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-probability 0.22.0 requires typing-extensions<4.6.0, but you have typing-extensions 4.9.0 which is incompatible.
Successfully installed typing_extensions-4.9.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (1.6.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.10/dist-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/lib/python3/dist-packages (from openai) (1.7.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from openai) (0.26.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from openai) (1.10.13)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from openai) (1.3.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.10/dist-packages (from openai) (4.66.1)
Requirement already satisfied: typing-extensions<5,>=4.7 in /usr/local/lib/python3.10/dist-packages (from openai) (4.9.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (3.6)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5,>=3.5.0->openai) (1.2.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.14.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.11.17)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [ ]:
!pip install typing-extensions --upgrade

Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (4.9.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [ ]:
from typing_extensions import Annotated, deprecated

import openai
EMBEDDINGS_MODEL = "text-embedding-ada-002"

In [ ]:
from openai import OpenAI
client = OpenAI(api_key='OPEN AI API KEY')

def get_embeddings(input):
  response = client.embeddings.create(
      input=input,
      model="text-embedding-ada-002"
  )

  return response.data[0].embedding

In [ ]:
import time
embeddings = []
run_count = 0
total = len(dataset)
while run_count <= total :
    for idx, row in enumerate(zip(dataset['Page Number'], dataset['Page Text'])):
        result = get_embeddings(row[1])
        embeddings.append(result)
        print(f'Progress : {len(embeddings)}/{total}')
        run_count += 1
        if run_count >= total:
          break
          #for instance max requests per minute allowed = 60 so after 50 requests we wait for 60s
        if run_count % 50 == 0 :
              time.sleep(20)

Progress : 1/117
Progress : 2/117
Progress : 3/117
Progress : 4/117
Progress : 5/117
Progress : 6/117
Progress : 7/117
Progress : 8/117
Progress : 9/117
Progress : 10/117
Progress : 11/117
Progress : 12/117
Progress : 13/117
Progress : 14/117
Progress : 15/117
Progress : 16/117
Progress : 17/117
Progress : 18/117
Progress : 19/117
Progress : 20/117
Progress : 21/117
Progress : 22/117
Progress : 23/117
Progress : 24/117
Progress : 25/117
Progress : 26/117
Progress : 27/117
Progress : 28/117
Progress : 29/117
Progress : 30/117
Progress : 31/117
Progress : 32/117
Progress : 33/117
Progress : 34/117
Progress : 35/117
Progress : 36/117
Progress : 37/117
Progress : 38/117
Progress : 39/117
Progress : 40/117
Progress : 41/117
Progress : 42/117
Progress : 43/117
Progress : 44/117
Progress : 45/117
Progress : 46/117
Progress : 47/117
Progress : 48/117
Progress : 49/117
Progress : 50/117
Progress : 51/117
Progress : 52/117
Progress : 53/117
Progress : 54/117
Progress : 55/117
Progress : 56/117
Progress : 57/117
Progress : 58/117
Progress : 59/117
Progress : 60/117
Progress : 61/117
Progress : 62/117
Progress : 63/117
Progress : 64/117
Progress : 65/117
Progress : 66/117
Progress : 67/117
Progress : 68/117
Progress : 69/117
Progress : 70/117
Progress : 71/117
Progress : 72/117
Progress : 73/117
Progress : 74/117
Progress : 75/117
Progress : 76/117
Progress : 77/117
Progress : 78/117
Progress : 79/117
Progress : 80/117
Progress : 81/117
Progress : 82/117
Progress : 83/117
Progress : 84/117
Progress : 85/117
Progress : 86/117
Progress : 87/117
Progress : 88/117
Progress : 89/117
Progress : 90/117
Progress : 91/117
Progress : 92/117
Progress : 93/117
Progress : 94/117
Progress : 95/117
Progress : 96/117
Progress : 97/117
Progress : 98/117
Progress : 99/117
Progress : 100/117
Progress : 101/117
Progress : 102/117
Progress : 103/117
Progress : 104/117
Progress : 105/117
Progress : 106/117
Progress : 107/117
Progress : 108/117
Progress : 109/117
Progress : 110/117
Progress : 111/117
Progress : 112/117
Progress : 113/117
Progress : 114/117
Progress : 115/117
Progress : 116/117
Progress : 117/117
Progress : 118/117

<h2>Adding the embeddings to the csv file</h3>

We store the embeddings in the csv file so that we dont have to make requests again and again for the embeddings

In [ ]:
print(len(embeddings))

118

Save embeddings to the csv

In [ ]:
import csv
import tempfile
import shutil

csv_file = 'dataset-1.csv'
temp_file = tempfile.NamedTemporaryFile(mode='w', delete=False)


with open(csv_file, 'r') as file_in, open(temp_file.name, 'w', newline='') as file_out:
    reader = csv.reader(file_in)
    writer = csv.writer(file_out)

    header = next(reader)
    header.append('Embeddings')
    writer.writerow(header)  # Write the modified header to the temporary file

    for row in reader:
        embedding_value = embeddings.pop(0)  # Get the next embedding value from the list
        row.append(embedding_value)  # Append the embedding value to the row
        writer.writerow(row)  # Write the modified row to the temporary file

shutil.move(temp_file.name, csv_file)

'dataset-1.csv'

<h2>Updated CSV file</h2>

In [ ]:
import pandas as pd
dataset = pd.read_csv('dataset-1.csv')
dataset.head()

,Page Number,Page Text,Embeddings
0,2,We\nAIM\nHIGHER\nThe National University of Sc...,"[0.00037002895260229707, -0.004527613986283541..."
1,3,Table of Content\n1 The University 1\n1. NUST ...,"[0.009081964381039143, -0.0028160621877759695,..."
2,4,4 Award of Master Degrees in Business 21\nAdmi...,"[-0.000777498702518642, -0.01749184913933277, ..."
3,5,8 NUST Social Media Accounts and IT Services 5...,"[-0.0017854692414402962, 0.004862336907535791,..."
4,6,CHAPTER 1\nThe University\n1. NUST at a Glance...,"[-0.0020116278901696205, -0.011365204118192196..."